/**
 * Database Types (Auto-generated by Supabase)
 *
 * To regenerate: npx supabase gen types typescript --project-id <project-id> > src/lib/database.types.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      colleges: {
        Row: {
          id: string
          name: string
          city: string
          state: string
          management_type: 'Government' | 'Private' | 'Trust' | 'Deemed'
          niac_rating: string | null
          nirf_rank: number | null
          established_year: number | null
          facilities: Json
          coordinates: unknown | null
          total_seats: number
          website_url: string | null
          description: string | null
          contact_email: string | null
          contact_phone: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          city: string
          state: string
          management_type: 'Government' | 'Private' | 'Trust' | 'Deemed'
          niac_rating?: string | null
          nirf_rank?: number | null
          established_year?: number | null
          facilities?: Json
          coordinates?: unknown | null
          total_seats?: number
          website_url?: string | null
          description?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          city?: string
          state?: string
          management_type?: 'Government' | 'Private' | 'Trust' | 'Deemed'
          niac_rating?: string | null
          nirf_rank?: number | null
          established_year?: number | null
          facilities?: Json
          coordinates?: unknown | null
          total_seats?: number
          website_url?: string | null
          description?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      courses: {
        Row: {
          id: string
          college_id: string
          name: string
          stream: string
          duration: string | null
          seats_available: number | null
          fees_structure: Json
          created_at: string
        }
        Insert: {
          id?: string
          college_id: string
          name: string
          stream: string
          duration?: string | null
          seats_available?: number | null
          fees_structure?: Json
          created_at?: string
        }
        Update: {
          id?: string
          college_id?: string
          name?: string
          stream?: string
          duration?: string | null
          seats_available?: number | null
          fees_structure?: Json
          created_at?: string
        }
      }
      cutoffs: {
        Row: {
          id: string
          college_id: string
          course_id: string | null
          year: number
          category: string
          quota: string
          round: number
          opening_rank: number | null
          closing_rank: number | null
          seats: number | null
          created_at: string
        }
        Insert: {
          id?: string
          college_id: string
          course_id?: string | null
          year: number
          category: string
          quota: string
          round: number
          opening_rank?: number | null
          closing_rank?: number | null
          seats?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          college_id?: string
          course_id?: string | null
          year?: number
          category?: string
          quota?: string
          round?: number
          opening_rank?: number | null
          closing_rank?: number | null
          seats?: number | null
          created_at?: string
        }
      }
      user_profiles: {
        Row: {
          user_id: string
          neet_rank: number | null
          neet_year: number | null
          category: string | null
          state: string | null
          preferences: Json
          onboarding_completed: boolean
          subscription_tier: 'free' | 'counseling' | 'premium'
          subscription_end_date: string | null
          daily_recommendation_count: number
          last_recommendation_reset: string
          created_at: string
          updated_at: string
        }
        Insert: {
          user_id: string
          neet_rank?: number | null
          neet_year?: number | null
          category?: string | null
          state?: string | null
          preferences?: Json
          onboarding_completed?: boolean
          subscription_tier?: 'free' | 'counseling' | 'premium'
          subscription_end_date?: string | null
          daily_recommendation_count?: number
          last_recommendation_reset?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          user_id?: string
          neet_rank?: number | null
          neet_year?: number | null
          category?: string | null
          state?: string | null
          preferences?: Json
          onboarding_completed?: boolean
          subscription_tier?: 'free' | 'counseling' | 'premium'
          subscription_end_date?: string | null
          daily_recommendation_count?: number
          last_recommendation_reset?: string
          created_at?: string
          updated_at?: string
        }
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string
          plan: 'free' | 'counseling' | 'premium'
          razorpay_subscription_id: string | null
          razorpay_payment_id: string | null
          razorpay_order_id: string | null
          status: 'active' | 'expired' | 'cancelled' | 'pending'
          start_date: string
          end_date: string | null
          auto_renew: boolean
          amount_paid: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          plan?: 'free' | 'counseling' | 'premium'
          razorpay_subscription_id?: string | null
          razorpay_payment_id?: string | null
          razorpay_order_id?: string | null
          status?: 'active' | 'expired' | 'cancelled' | 'pending'
          start_date?: string
          end_date?: string | null
          auto_renew?: boolean
          amount_paid?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          plan?: 'free' | 'counseling' | 'premium'
          razorpay_subscription_id?: string | null
          razorpay_payment_id?: string | null
          razorpay_order_id?: string | null
          status?: 'active' | 'expired' | 'cancelled' | 'pending'
          start_date?: string
          end_date?: string | null
          auto_renew?: boolean
          amount_paid?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      favorites: {
        Row: {
          id: string
          user_id: string
          college_id: string
          type: 'college' | 'course' | 'cutoff'
          notes: string | null
          tags: string[]
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          college_id: string
          type?: 'college' | 'course' | 'cutoff'
          notes?: string | null
          tags?: string[]
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          college_id?: string
          type?: 'college' | 'course' | 'cutoff'
          notes?: string | null
          tags?: string[]
          created_at?: string
        }
      }
      college_notes: {
        Row: {
          id: string
          user_id: string
          college_id: string
          content: string
          tags: string[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          college_id: string
          content: string
          tags?: string[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          college_id?: string
          content?: string
          tags?: string[]
          created_at?: string
          updated_at?: string
        }
      }
      watchlist: {
        Row: {
          id: string
          user_id: string
          college_id: string
          priority: 'high' | 'medium' | 'low'
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          college_id: string
          priority?: 'high' | 'medium' | 'low'
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          college_id?: string
          priority?: 'high' | 'medium' | 'low'
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: 'deadline' | 'seat_alert' | 'cutoff_update' | 'recommendation' | 'system'
          title: string
          message: string
          link: string | null
          read: boolean
          priority: 'high' | 'medium' | 'low'
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: 'deadline' | 'seat_alert' | 'cutoff_update' | 'recommendation' | 'system'
          title: string
          message: string
          link?: string | null
          read?: boolean
          priority?: 'high' | 'medium' | 'low'
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: 'deadline' | 'seat_alert' | 'cutoff_update' | 'recommendation' | 'system'
          title?: string
          message?: string
          link?: string | null
          read?: boolean
          priority?: 'high' | 'medium' | 'low'
          created_at?: string
        }
      }
      recommendation_cache: {
        Row: {
          id: string
          user_id: string
          college_id: string
          match_score: number
          safety_level: 'safe' | 'moderate' | 'reach' | 'dream'
          factors: Json
          reasons: string[]
          is_hidden_gem: boolean
          is_early_advantage: boolean
          created_at: string
          expires_at: string
        }
        Insert: {
          id?: string
          user_id: string
          college_id: string
          match_score: number
          safety_level: 'safe' | 'moderate' | 'reach' | 'dream'
          factors?: Json
          reasons?: string[]
          is_hidden_gem?: boolean
          is_early_advantage?: boolean
          created_at?: string
          expires_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          college_id?: string
          match_score?: number
          safety_level?: 'safe' | 'moderate' | 'reach' | 'dream'
          factors?: Json
          reasons?: string[]
          is_hidden_gem?: boolean
          is_early_advantage?: boolean
          created_at?: string
          expires_at?: string
        }
      }
      live_seat_updates: {
        Row: {
          id: string
          college_id: string
          course_id: string
          round: number
          seats_filled: number
          seats_total: number
          last_rank_filled: number | null
          filling_rate: number | null
          updated_at: string
        }
        Insert: {
          id?: string
          college_id: string
          course_id: string
          round: number
          seats_filled?: number
          seats_total: number
          last_rank_filled?: number | null
          filling_rate?: number | null
          updated_at?: string
        }
        Update: {
          id?: string
          college_id?: string
          course_id?: string
          round?: number
          seats_filled?: number
          seats_total?: number
          last_rank_filled?: number | null
          filling_rate?: number | null
          updated_at?: string
        }
      }
      subscription_plans: {
        Row: {
          id: string
          name: string
          price: number
          duration: 'monthly' | 'seasonal' | 'annual'
          features: Json
          is_active: boolean
          created_at: string
        }
        Insert: {
          id: string
          name: string
          price: number
          duration: 'monthly' | 'seasonal' | 'annual'
          features?: Json
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          price?: number
          duration?: 'monthly' | 'seasonal' | 'annual'
          features?: Json
          is_active?: boolean
          created_at?: string
        }
      }
    }
    Views: {
      college_stats: {
        Row: {
          id: string
          name: string
          state: string
          management_type: 'Government' | 'Private' | 'Trust' | 'Deemed'
          nirf_rank: number | null
          course_count: number
          cutoff_records: number
          lowest_cutoff: number | null
          avg_cutoff: number | null
          latest_year: number | null
          favorite_count: number
        }
      }
    }
    Functions: {
      has_premium_access: {
        Args: { p_user_id: string }
        Returns: boolean
      }
      create_notification: {
        Args: {
          p_user_id: string
          p_type: string
          p_title: string
          p_message: string
          p_link?: string
          p_priority?: string
        }
        Returns: string
      }
      reset_recommendation_count: {
        Args: {}
        Returns: void
      }
      clean_expired_recommendations: {
        Args: {}
        Returns: void
      }
      refresh_college_stats: {
        Args: {}
        Returns: void
      }
    }
    Enums: {
      subscription_tier: 'free' | 'counseling' | 'premium'
      subscription_status: 'active' | 'expired' | 'cancelled' | 'pending'
      management_type: 'Government' | 'Private' | 'Trust' | 'Deemed'
      safety_level: 'safe' | 'moderate' | 'reach' | 'dream'
      notification_type: 'deadline' | 'seat_alert' | 'cutoff_update' | 'recommendation' | 'system'
      priority_level: 'high' | 'medium' | 'low'
    }
  }
}
