# Guardian Match Validation Configuration
# 100% Accuracy System with 9 Free LLM Models

# ============================================================================
# VALIDATION RULES
# ============================================================================
rules:
  # CRITICAL RULES (Auto-BLOCK)
  - id: R01
    name: State Match
    description: Seat state must match master college state
    severity: CRITICAL
    enabled: true
    action: BLOCK

  - id: R02
    name: Stream Match
    description: Dental/Medical course must match college type
    severity: CRITICAL
    enabled: true
    action: BLOCK

  - id: R03
    name: Score Floor
    description: Match score must be >= threshold
    severity: CRITICAL
    enabled: true
    threshold: 0.70
    action: BLOCK

  - id: R04
    name: Name Consistency
    description: Same raw name must map to same master
    severity: CRITICAL
    enabled: true
    action: BLOCK

  - id: R05
    name: Cardinality
    description: One seat record must match exactly one master
    severity: CRITICAL
    enabled: true
    action: BLOCK

  - id: R06
    name: Code Conflict
    description: If college code present, must match master ID
    severity: CRITICAL
    enabled: true
    action: BLOCK

  # WARNING RULES (Send to QUARANTINE for LLM verification)
  - id: R07
    name: Weak Address
    description: Address overlap score below threshold
    severity: WARNING
    enabled: true
    threshold: 0.20
    action: QUARANTINE

  - id: R08
    name: Name Drift
    description: Name similarity below threshold
    severity: WARNING
    enabled: true
    threshold: 0.75
    action: QUARANTINE

  - id: R09
    name: Statistical Outlier
    description: Match is a statistical anomaly
    severity: WARNING
    enabled: true
    z_score_threshold: 3.0
    action: QUARANTINE

  - id: R10
    name: AI Unvalidated
    description: Match method contains 'unvalidated'
    severity: WARNING
    enabled: true
    action: QUARANTINE

  - id: R11
    name: Low Confidence
    description: Match score in warning zone
    severity: WARNING
    enabled: true
    min_threshold: 0.70
    max_threshold: 0.85
    action: QUARANTINE

  - id: R12
    name: No Address Low Score
    description: Missing address with score below threshold
    severity: WARNING
    enabled: true
    score_threshold: 0.95
    action: QUARANTINE

  # CRITICAL: Multi-campus address mismatch (catches false matches)
  - id: R13
    name: Multi-Campus Address Mismatch
    description: Same college_id matched to different physical locations
    severity: CRITICAL
    enabled: true
    action: BLOCK

  # CRITICAL: Same-ID Multi-Address Detection (pattern-level check)
  - id: R14
    name: Same-ID Multi-Address Detection
    description: Detects when same master_college_id is matched to records from different cities/districts
    severity: CRITICAL
    enabled: true
    action: BLOCK

  # CRITICAL: Gross Name Mismatch (catches PGIMER → AIIMS type false matches)
  - id: R15
    name: Gross Name Mismatch
    description: Catches when seat name has very low similarity to master name (below 40%)
    severity: CRITICAL
    enabled: true
    threshold: 0.40
    action: BLOCK

  # CRITICAL: Cross-State Mismatch (catches BIHAR → CHHATTISGARH type false matches)
  - id: R16
    name: Cross-State Mismatch
    description: Catches when seat state is different from master college state
    severity: CRITICAL
    enabled: true
    action: BLOCK

# ============================================================================
# LLM VERIFICATION COUNCIL
# ============================================================================
verification_council:
  # Flexible settings
  timeout: 120 # seconds per request
  batch_size: 20 # records per batch (adjustable)
  max_output_tokens: 8192 # flexible output

  # 9 Models - All Free
  models:
    # Round 1: Fast Verification (5 models)
    round_1:
      - id: 1
        name: google/gemini-2.0-flash-exp:free
        role: fast_verifier
        max_tokens: 8000
        batch_size: 10

      - id: 2
        name: amazon/nova-2-lite-v1:free
        role: large_context
        max_tokens: 65536
        batch_size: 30

      - id: 3
        name: qwen/qwen3-coder:free
        role: json_accuracy
        max_tokens: 65536
        batch_size: 30

      - id: 4
        name: mistralai/mistral-small-3.1-24b-instruct:free
        role: reasoning
        max_tokens: 16384
        batch_size: 15

      - id: 5
        name: google/gemma-3-27b-it:free
        role: alternative_view
        max_tokens: 8192
        batch_size: 20

    # Standby Failover (instant retry if Round 1 model fails)
    standby:
      - id: 6
        name: tngtech/deepseek-r1t-chimera:free
        role: o1_reasoning
        max_tokens: 16384
        batch_size: 20

      - id: 7
        name: kwaipilot/kat-coder-pro:free
        role: high_output
        max_tokens: 32768
        batch_size: 25

    # Round 2: Deep Verification (2 specialist models)
    round_2:
      - id: 8
        name: openai/gpt-oss-120b:free
        role: o4_level_reasoning
        max_tokens: 16384
        batch_size: 15

      - id: 9
        name: alibaba/tongyi-deepresearch-30b-a3b:free
        role: deep_research
        max_tokens: 8192
        batch_size: 10

  # Voting Rules
  voting:
    round_1:
      models: [1, 2, 3, 4, 5]
      approve_threshold: 5 # unanimous
      escalate_threshold: 4 # 4/5 = escalate
      reject_threshold: 3 # <4 = reject

    round_2:
      models: [8, 9] # Add to Round 1 votes
      approve_threshold: 6 # 6/7 total = approve
      reject_threshold: 5 # <6 = reject

    standby_failover:
      models: [6, 7]
      trigger: model_failure
      action: instant_retry

# ============================================================================
# PROCESSING CONFIGURATION
# ============================================================================
processing:
  parallel_workers: 7 # One per API key
  retry_on_failure: true
  max_retries: 3
  retry_delay: 5 # seconds

  # Batch optimization
  group_by:
    - state
    - college_name
    - address

  # Expected outcomes
  targets:
    pass_rate: 0.95
    quarantine_rate: 0.04
    block_rate: 0.01
    false_positive_rate: 0.001
